# Module: golang
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-golang.html

- module: golang
  metricsets:
    - expvar
    - heap
  period: 10s
  hosts: ["192.168.208.4:6060"]
  heap.path: "/debug/vars"
  expvar:
    namespace: "example"
    path: "/debug/vars"
