# Module: prometheus
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-prometheus.html

- module: prometheus
  period: 10s
  hosts: ["192.168.208.11:9443", "192.168.208.8:9443", "192.168.208.9:9443", "192.168.208.10:9443"]
  metrics_path: /metrics
  #username: "user"
  #password: "secret"

  # This can be used for service account based authorization:
  #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #ssl.certificate_authorities:
  #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
